apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TimRoos98/ArgoCD_Project.git
    targetRevision: HEAD
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
